version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=koadb
      - DB_PORT=3306

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=koadb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
